### ISSUE TITLE
Bug in CodingManager / OriginWidget

### ISSUE THREAD

**Issue by govertbuijs** [TESTARtool/TESTAR_dev#202]
I'm trying to merge the master into the govert_dev branch (webdriver). 
I run into this error:

```Java
No origin widget found for action role: 
LeftDrag
Drag (1634.5, 43.5) To (1634.5, 375.2)
org.fruit.alayer.exceptions.NoSuchTagException: Tag 'OriginWidget' unavailable!
	at org.fruit.alayer.TaggableBase.get(TaggableBase.java:54)
	at es.upv.staq.testar.CodingManager.lambda$buildIDs$0(CodingManager.java:210)
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at es.upv.staq.testar.CodingManager.buildIDs(CodingManager.java:211)
	at org.fruit.monkey.DefaultProtocol.runSpyLoop(DefaultProtocol.java:961)
	at org.fruit.monkey.DefaultProtocol.run(DefaultProtocol.java:270)
	at org.fruit.monkey.DefaultProtocol.run(DefaultProtocol.java:120)
	at org.fruit.monkey.Main.startTestar(Main.java:355)
	at org.fruit.monkey.Main.main(Main.java:139)
```

In CodingManager.java, i see this code and fail to understand how this could ever work,  
as the return statement causes the exception again.

```Java
try {  
    action.get(Tags.OriginWidget);  
}  
catch (NoSuchTagException ex) {  
    System.out.println("No origin widget found for action role: ");  
    System.out.println(action.get(Tags.Role));  
    System.out.println(action.get(Tags.Desc));  
}  
return action.get(Tags.OriginWidget).get(Tags.Path);  
```

**Comment by ferpasri** [comment]
Hi,

Can u add this code at the end of 

> testar/src/org/testar/protocols/WebdriverProtocol.java

`/**
     * Adds sliding actions (like scroll, drag and drop) to the given Set of Actions
     * @param actions
     * @param ac
     * @param scrollArrowSize
     * @param scrollThick
     * @param widget
     */
    protected void addSlidingActions(Set<Action> actions, StdActionCompiler ac, double scrollArrowSize, double scrollThick, Widget widget, State state){
        Drag[] drags = null;
        //If there are scroll (drags/drops) actions possible
        if((drags = widget.scrollDrags(scrollArrowSize,scrollThick)) != null){
            //For each possible drag, create an action and add it to the derived actions
            for (Drag drag : drags){
                //Create a slide action with the Action Compiler, and add it to the set of derived actions
                actions.add(ac.slideFromTo(
                        new AbsolutePosition(Point.from(drag.getFromX(),drag.getFromY())),
                        new AbsolutePosition(Point.from(drag.getToX(),drag.getToY())),
                        widget
                ));

            }
        }
    }`

This should create the Tag.OriginWidget for Drags Actions

**Comment by admulders** [comment]
Govert is right. It's not a good piece of code. I think I was testing and when I got things working for my particular problem, I forgot about it. I fixed it by filtering the items without the originWidget set.

It's commit bf71758bfeb9715093d3ce888c7e81522609b0fd on my state_model_dev branch.

```
filter(action -> {
					try {
						action.get(Tags.OriginWidget).get(Tags.Path);
						return true;
					}
					catch (NoSuchTagException ex) {
						System.out.println("No origin widget found for action role: ");
						System.out.println(action.get(Tags.Role));
						System.out.println(action.get(Tags.Desc));
						return false;
					}
				}).
				sorted(Comparator.comparing(action -> action.get(Tags.OriginWidget).get(Tags.Path))).
```

(Can't get the indentation right here)

**Comment by ferpasri** [comment]
Solved and merged into master branch
