### ISSUE TITLE
[Webdriver] Exception with web pages that use Prototype.JS

### ISSUE THREAD

**Issue by ferpasri** [TESTARtool/TESTAR_dev#203]
Versión 77.0.3865.75 (Build oficial) (64 bits)
ChromeDriver 77.0.3865.40

Steps to reproduce:
- branch: govert_dev
- Use Spy mode into
- https://intranet.upv.es/pls/soalu/est_intranet.ni_portal_n?P_IDIOMA=c

```
org.fruit.alayer.exceptions.StateBuildException: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
        at org.fruit.alayer.webdriver.WdStateBuilder.apply(WdStateBuilder.java:62)
        at org.fruit.alayer.webdriver.WdStateBuilder.apply(WdStateBuilder.java:39)
        at org.fruit.monkey.DefaultProtocol.runSpyLoop(DefaultProtocol.java:938)
        at org.fruit.monkey.DefaultProtocol.run(DefaultProtocol.java:268)
        at org.fruit.monkey.DefaultProtocol.run(DefaultProtocol.java:120)
        at org.fruit.monkey.Main.startTestar(Main.java:349)
        at org.fruit.monkey.Main.main(Main.java:133)

**Comment by govertbuijs** [comment]
I can't fix this robustly for version 1.6.x, the code interferes with the web-extension too much.
The web-extension and Prototype.js 1.7 and up seem to work.

**Comment by ferpasri** [comment]
We leave it as a known issue, the user is additionally informed in the cmd

![image](https://user-images.githubusercontent.com/32359126/94988542-56754700-056e-11eb-9a49-80f0049fe857.png)

**Comment by ferpasri** [comment]
- Prototype web technology is being used in less than 0.5% of web pages

https://w3techs.com/technologies/overview/javascript_library  
https://en.wikipedia.org/wiki/Prototype_JavaScript_Framework#cite_note-1  

- And this 1.6.X version is 15 years old technology.

For these reasons, we decided not to add extra complexity to the TESTAR+chromedriver code.  
A workaround is to use the old Internet Explorer browser + desktop generic protocol.
