### ISSUE TITLE
java.lang.UnsatisfiedLinkError when starting to generate tests

### ISSUE THREAD

**Issue by digiofficerobin** [TESTARtool/TESTAR_dev#258]
Hi, I am a first time user of Testar en do not have many experience with Java development.

I have downloaded Tester for Windows 7 binaries and unpacked the files, and installed Java 8 update 291.

When I start ..\bin\testar.bat I get the following warnings and an exception. when I start to generate tests.
```
Listening for transport dt_socket at address: 5005
Java version is not JDK 1.8, please install
Test settings is <.\settings\01_desktop_generic_pure_random\test.settings>
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/D:/Tools/Testar/testar/lib/jaxb-impl-2.3.0.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Saved <.\settings\01_desktop_generic_pure_random\test.settings>
Saved current settings to <.\settings\01_desktop_generic_pure_random\test.settings>
Loading external lib ... windows.dll
[START] Running processes (141):
SUT is running after <2046> ms ... waiting UI to be accessible
SUT accessible after <2719> ms
[END] Running processes (142):
Will kill process: PID <25324> HANDLE <4516> DESC <DllHost.exe>
Saved <.\settings\01_desktop_generic_pure_random\test.settings>
Saved current settings to <.\settings\01_desktop_generic_pure_random\test.settings>
[START] Running processes (141):
SUT is running after <2041> ms ... waiting UI to be accessible
SUT accessible after <2642> ms
Main: Exception caught
java.lang.UnsatisfiedLinkError: 'long org.fruit.alayer.windows.Windows.MonitorFromWindow(long, long)'
        at org.fruit.alayer.windows.Windows.MonitorFromWindow(Native Method)
        at org.fruit.alayer.windows.Windows10.getDisplayScale(Windows10.java:43)
        at org.fruit.alayer.AWTCanvas.fromScreenshot(AWTCanvas.java:122)
        at es.upv.staq.testar.ProtocolUtil.getStateshotBinary(ProtocolUtil.java:260)
        at es.upv.staq.testar.ProtocolUtil.getStateshot(ProtocolUtil.java:238)
        at org.fruit.monkey.DefaultProtocol.setStateScreenshot(DefaultProtocol.java:1385)
        at org.fruit.monkey.DefaultProtocol.getState(DefaultProtocol.java:1355)
        at org.testar.protocols.DesktopProtocol.getState(DesktopProtocol.java:97)
        at Protocol_desktop_generic_pure_random.getState(Protocol_desktop_generic_pure_random.java:116)
        at org.fruit.monkey.DefaultProtocol.runGenerateOuterLoop(DefaultProtocol.java:678)
        at org.fruit.monkey.DefaultProtocol.run(DefaultProtocol.java:253)
        at org.fruit.monkey.DefaultProtocol.run(DefaultProtocol.java:98)
        at org.fruit.monkey.Main.startTestar(Main.java:380)
        at org.fruit.monkey.Main.main(Main.java:139)
```

What can I do to solve these warnings and exceptions?

**Comment by pekkakaho** [comment]
Hi,

Did you download this package?
https://github.com/TESTARtool/TESTAR_dev/releases/download/v2.2.17/testar_master_2.2.17_windows7.zip

Best regards,
-Pekka

**Comment by digiofficerobin** [comment]
Hi,

Yes, that is the one that I downloaded.

I get also the same error when I try the binaries in your link.

Kind regards,
Robin

**Comment by pekkakaho** [comment]
Hi,

Are you running it on Windows 7? There is a separate installation package for Win 10: https://testar.org/images/development/testar_master_latest.zip

BR,
-Pekka

**Comment by digiofficerobin** [comment]
Ah, oke, thanks, this one works indeed!

**Comment by ferpasri** [comment]
I have renamed and added "windows10" in the https://testar.org/download page and in the github releases.
Since now it seems to work, we can close this issue.
