### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by oikarinen-fs** [TESTARtool/TESTAR_dev#278]
TESTAR 2.3.4 (1-Jul-2021) f-secure_dev branch (732a6cd896f89553c30e91e5bfc965f1e6e9ef43)
Windows 10 Enterprise build 19041
OpenJDK 1.8.0 (java-1.8.0-openjdk-1.8.0.292-1.b10)

Steps to reproduce: Start Testar GUI from CMD, run comparing tool, start generate mode.

Note: Later on same problem appeared even without running comparing tool first.
Problem isn't consistent. Sometimes generate mode starts normally without crashing.

Tried fixes: Increase memory on start parameters on testar.bat with: `"-Xmx8G" "-Xms4G" "-XX:NewSize=3G" "-XX:MaxNewSize=3G"` without help.

Error message:
```
[START] Running processes (34):
Main: Exception caught
java.lang.OutOfMemoryError: Java heap space
        at sun.awt.windows.WRobotPeer.getRGBPixels(WRobotPeer.java:73)
        at java.awt.Robot.createScreenCapture(Robot.java:438)
        at org.fruit.alayer.AWTCanvas.fromScreenshot(AWTCanvas.java:127)
        at es.upv.staq.testar.ProtocolUtil.getStateshotBinary(ProtocolUtil.java:269)
        at es.upv.staq.testar.ProtocolUtil.getStateshot(ProtocolUtil.java:239)
        at org.fruit.monkey.WindowsWindowTitleSutConnector.getStateByWindowTitle(WindowsWindowTitleSutConnector.java:94)
        at org.fruit.monkey.WindowsWindowTitleSutConnector.startOrConnectSut(WindowsWindowTitleSutConnector.java:67)
        at org.fruit.monkey.DefaultProtocol.startSystem(DefaultProtocol.java:1440)
        at Protocol_desktop_fsecure.startSystem(Protocol_desktop_fsecure.java:86)
        at org.fruit.monkey.DefaultProtocol.startSutIfNotRunning(DefaultProtocol.java:549)
        at org.fruit.monkey.DefaultProtocol.runGenerateOuterLoop(DefaultProtocol.java:678)
        at org.fruit.monkey.DefaultProtocol.run(DefaultProtocol.java:264)
        at org.fruit.monkey.DefaultProtocol.run(DefaultProtocol.java:99)
        at org.fruit.monkey.Main.startTestar(Main.java:382)
        at org.fruit.monkey.Main.main(Main.java:139)
Exception in thread "main" java.lang.NullPointerException
        at java.lang.Throwable.printStackTrace(Throwable.java:654)
        at java.lang.Throwable.printStackTrace(Throwable.java:644)
        at org.fruit.monkey.Main.startTestar(Main.java:388)
        at org.fruit.monkey.Main.main(Main.java:139)
```

**Comment by oikarinen-fs** [comment]
Tried to reproduce the problem, but this time it crashed every time from beginning. Deleted Testar and OrientDB. Unzipped clean versions, rebooted and tried to run generate mode but crashing keeps happening. Tried with local and remote db. Tried default start parameters and later on added "-Xmx8G" "-Xms4G", no difference.

**Comment by oikarinen-fs** [comment]
Error message from debugger:
[testar-crash.txt](https://github.com/TESTARtool/TESTAR_dev/files/7116125/testar-crash.txt)

**Comment by ferpasri** [comment]
@oikarinen-fs Hi Joona,
to execute TESTAR do you use the gradle task `runTestar` ?

To try to replicate the issue locally and prepare a solution.

**Comment by oikarinen-fs** [comment]
Hey @ferpasri

Normally I run testar.bat from CMD. But to gather more info I used `gradle runTestar --debug` to produce testar-crash.txt file.

**Comment by pekkakaho** [comment]
The model difference functionality has been moved to another program and the memory issues related to that have been fixed.
