### ISSUE TITLE
Bug: relative paths on `Application name` field may lead to `FileNotFoundException`.

### ISSUE THREAD

**Issue by Polo3cat** [TESTARtool/TESTAR_dev#357]
## Version
Testar 2.6.3

## Description
Testar's front-end tool for generating configurations crashes if the application name given is a relative directory that points nowhere.

## Reproduction
The following screenshot shows the state in which the application was before running.

![image](https://github.com/TESTARtool/TESTAR_dev/assets/11423091/8f51d984-68de-457a-85ec-71a4c8e9e2ec)

With the above set, running in generation mode would lead to the following backtrace:
```
C:\Testar\bin>testar
Listening for transport dt_socket at address: 5005
Detected Java version is : C:\Program Files\Eclipse Adoptium\jdk-11.0.19.7-hotspot
Test settings is <.\settings\01_desktop_calculator\test.settings>
Saved <.\settings\01_desktop_calculator\test.settings>
Saved current settings to <.\settings\01_desktop_calculator\test.settings>
Used directory compileProtocol settingsDir = .\settings\ compileDir = C:\Testar\bin\.\settings\01_desktop_calculator
2023-05-10-18:40:28.140 TESTAR initializing with the given protocol settings
Loading external lib ... windows.dll
java.io.FileNotFoundException: .\output\2023-05-10_18h40m28s_..\..\..\..\..\HTMLreports\2023-05-10_18h40m28s_..\..\..\..\..\_sequence_1.html (Access is denied)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at java.base/java.io.PrintWriter.<init>(PrintWriter.java:208)
        at java.base/java.io.PrintWriter.<init>(PrintWriter.java:248)
        at org.testar.reporting.HtmlSequenceReport.<init>(HtmlSequenceReport.java:85)
        at org.testar.monkey.AbstractProtocol.getReporter(AbstractProtocol.java:84)
        at org.testar.protocols.DesktopProtocol.preSequencePreparations(DesktopProtocol.java:67)
        at Protocol_01_desktop_calculator.preSequencePreparations(Protocol_01_desktop_calculator.java:71)
        at org.testar.monkey.GenerateMode.runGenerateOuterLoop(GenerateMode.java:77)
        at org.testar.monkey.DefaultProtocol.run(DefaultProtocol.java:259)
        at org.testar.monkey.DefaultProtocol.run(DefaultProtocol.java:94)
        at org.testar.monkey.Main.startTestar(Main.java:383)
        at org.testar.monkey.Main.main(Main.java:149)
[START] Running processes (30):
2023-05-10-18:40:30.347 SUT is running after <2027> ms ... waiting UI to be accessible
2023-05-10-18:40:30.672 SUT accessible after <2359> ms
java.io.FileNotFoundException: .\output\2023-05-10_18h40m28s_..\..\..\..\..\logs\2023-05-10_18h40m28s_..\..\..\..\..\_sequence_1.log (Access is denied)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at org.testar.monkey.DefaultProtocol.getAndStoreGeneratedSequence(DefaultProtocol.java:485)
        at org.testar.monkey.GenerateMode.runGenerateOuterLoop(GenerateMode.java:86)
        at org.testar.monkey.DefaultProtocol.run(DefaultProtocol.java:259)
        at org.testar.monkey.DefaultProtocol.run(DefaultProtocol.java:94)
        at org.testar.monkey.Main.startTestar(Main.java:383)
        at org.testar.monkey.Main.main(Main.java:149)
ERROR: Adding the State number 0 in the HTML report
Thread: name=main,id=1, TESTAR throws exception
java.lang.NullPointerException
        at org.testar.reporting.HtmlSequenceReport.write(HtmlSequenceReport.java:338)
        at org.testar.reporting.HtmlSequenceReport.writeStateIntoReport(HtmlSequenceReport.java:180)
        at org.testar.reporting.HtmlSequenceReport.addState(HtmlSequenceReport.java:159)
        at org.testar.protocols.DesktopProtocol.getState(DesktopProtocol.java:101)
        at Protocol_01_desktop_calculator.getState(Protocol_01_desktop_calculator.java:112)
        at org.testar.monkey.GenerateMode.runGenerateOuterLoop(GenerateMode.java:95)
        at org.testar.monkey.DefaultProtocol.run(DefaultProtocol.java:259)
        at org.testar.monkey.DefaultProtocol.run(DefaultProtocol.java:94)
        at org.testar.monkey.Main.startTestar(Main.java:383)
        at org.testar.monkey.Main.main(Main.java:149)
[END] Running processes (31):
Will kill process: PID <7004> HANDLE <3696> DESC <java.exe>
Exception <null> has been caught; Stack trace:
        [1] org.testar.reporting.HtmlSequenceReport.write(HtmlSequenceReport.java:338)
        [2] org.testar.reporting.HtmlSequenceReport.writeStateIntoReport(HtmlSequenceReport.java:180)
        [3] org.testar.reporting.HtmlSequenceReport.addState(HtmlSequenceReport.java:159)
        [4] org.testar.protocols.DesktopProtocol.getState(DesktopProtocol.java:101)
        [5] Protocol_01_desktop_calculator.getState(Protocol_01_desktop_calculator.java:112)
        [6] org.testar.monkey.GenerateMode.runGenerateOuterLoop(GenerateMode.java:95)
        [7] org.testar.monkey.DefaultProtocol.run(DefaultProtocol.java:259)
        [8] org.testar.monkey.DefaultProtocol.run(DefaultProtocol.java:94)
        [9] org.testar.monkey.Main.startTestar(Main.java:383)
        [10] org.testar.monkey.Main.main(Main.java:149)
Exception in thread "main" java.lang.NullPointerException
        at org.testar.serialisation.LogSerialiser.flush(LogSerialiser.java:136)
        at org.testar.monkey.DefaultProtocol.emergencyTerminateTestSequence(DefaultProtocol.java:603)
        at org.testar.monkey.GenerateMode.runGenerateOuterLoop(GenerateMode.java:152)
        at org.testar.monkey.DefaultProtocol.run(DefaultProtocol.java:259)
        at org.testar.monkey.DefaultProtocol.run(DefaultProtocol.java:94)
        at org.testar.monkey.Main.startTestar(Main.java:383)
        at org.testar.monkey.Main.main(Main.java:149)
```

## Expectation
I would expect the application not to crash.

**Comment by ferpasri** [comment]
Fixed in #360
